import type { BusinessType } from "../businessType";

/** The public "billing software for <trade>" pages (app/billing-software): what a shop owner
 * searching for software for their trade finds. Every feature named here is in the app and shown in
 * that trade's training video; nothing is promised that the app doesn't do. */
export type Vertical = {
  type: BusinessType;
  slug: string;
  /** The trade's page on the main site, www.theray.in, where it lives: this site's address for it
   * redirects there permanently (next.config), so the two never compete in search. Only a trade
   * the main site has no page for is shown here. */
  mainSite?: string;
  /** "Kirana store" — used in sentences. */
  trade: string;
  title: string;
  description: string;
  h1: string;
  intro: string;
  /** How people search for it, in their words. */
  alsoKnownAs: string[];
  features: { title: string; body: string }[];
  faqs: { q: string; a: string }[];
  /** Training videos for this trade, first one shown. */
  videos: string[];
};

export const VERTICALS: Vertical[] = [
  {
    type: "grocery",
    slug: "kirana-store",
    mainSite: "https://www.theray.in/billing-software/kirana-grocery-store",
    trade: "kirana store",
    title: "Kirana Store Billing Software with GST, Udhar Khata & Stock",
    description: "Billing app for kirana and grocery shops: fast counter billing, barcode scan, udhar khata with WhatsApp reminders, stock and reorder, GSTR-1/3B. Free 14-day trial.",
    h1: "Billing software for kirana & grocery stores",
    intro: "Bill a customer in seconds at the counter, keep every customer's udhar in one khata, know which items are running low, and file GST without a separate accountant's app — on the phone you already have.",
    alsoKnownAs: ["kirana billing app", "grocery shop billing software", "udhar khata app", "general store billing app"],
    features: [
      { title: "Fast Billing counter", body: "Tap item tiles to bill in seconds; scan barcodes or search by name. Quantity, discount and GST are worked out for you." },
      { title: "Udhar khata with reminders", body: "Part payment goes on the customer's khata; send a WhatsApp reminder with the balance and a link to their statement." },
      { title: "Stock and reorder", body: "Stock falls with every bill; low-stock items are listed and turn into a ready purchase order for your supplier." },
      { title: "Barcode labels", body: "Print barcode labels for loose and packed items; weighing-scale labels can be scanned straight into the bill." },
      { title: "GST reports", body: "GSTR-1, GSTR-3B and the purchase register from your own bills, ready for your CA as Excel or PDF." },
      { title: "Loyalty and birthdays", body: "Points on every bill, redeemed as a discount, and a reminder on regular customers' birthdays." },
    ],
    faqs: [
      { q: "Can I keep udhar (credit) for customers?", a: "Yes. Any bill can be part paid; the rest goes on the customer's khata. You see what each customer owes, how old it is, and can send a WhatsApp reminder in one tap." },
      { q: "Does it work with a barcode scanner?", a: "Yes — a USB or Bluetooth scanner, or the phone's camera. In the Android app the phone's own Google scanner is used, which reads barcodes quickly even in poor light." },
    ],
    videos: ["02", "30"],
  },
  {
    type: "mart",
    slug: "supermarket",
    mainSite: "https://www.theray.in/billing-software/supermarket",
    trade: "supermarket",
    title: "Supermarket & Mini Mart Billing Software — Fast POS with MRP Offers",
    description: "POS billing for supermarkets and marts: quick counter billing, MRP and offer prices, bulk rates, buy X get Y, stock audit and reorder, GST reports. Free 14-day trial.",
    h1: "Billing software for supermarkets & marts",
    intro: "A quick counter for busy hours, offers that apply themselves, and a proper stock count — so the shelf, the system and the cash all agree.",
    alsoKnownAs: ["supermarket POS software", "mart billing app", "retail POS India"],
    features: [
      { title: "Counter billing for rush hours", body: "Big item tiles, barcode scan and one-tap payment keep the queue moving." },
      { title: "MRP, offer price and bulk rates", body: "The bill shows MRP, your price and the customer's saving; buy more and the bulk rate applies by itself." },
      { title: "Buy X get Y", body: "Set '2 lo 1 free' style schemes once; the free item is added and shown on the bill." },
      { title: "Stock audit", body: "Count shelves section by section, see what doesn't match, and settle the difference with a reason." },
      { title: "Reorder in one tap", body: "Low-stock items become a pre-filled purchase you only need to check and send." },
      { title: "Profit leak", body: "Spot items sold below cost, missing stock and slow movers before they cost you more." },
    ],
    faqs: [
      { q: "Can more than one counter bill at the same time?", a: "Yes. Each cashier logs in with their own staff login and permissions; all bills go into the same stock and reports." },
      { q: "Does it show MRP and discount on the bill?", a: "Yes. The invoice shows MRP, your price and the saving, and you can choose A4 or 58/80 mm thermal formats." },
    ],
    videos: ["03", "30"],
  },
  {
    type: "hardware",
    slug: "hardware-shop",
    mainSite: "https://www.theray.in/billing-software/hardware-shop",
    trade: "hardware shop",
    title: "Hardware & Building Material Shop Billing Software with Contractor Udhar",
    description: "Billing for hardware, electrical, paint and building material shops: contractor udhar khata, warranty records, delivery challans, bulk rates, GST bills. Free trial.",
    h1: "Billing software for hardware & building material shops",
    intro: "Contractors who pay later, items under warranty and goods sent on a challan before the bill — The Ray keeps all of it straight.",
    alsoKnownAs: ["hardware shop billing software", "electrical shop billing app", "building material billing software", "paint shop billing"],
    features: [
      { title: "Contractor khata", body: "Running udhar per contractor with a credit limit; a warning before a bill goes over it." },
      { title: "Warranty records", body: "Warranty is saved with the bill; look it up later by the customer's phone number." },
      { title: "Delivery challans", body: "Send goods on a challan now and make one bill for many challans later." },
      { title: "Bulk rates", body: "Different rates for bigger quantities, applied automatically on the bill." },
      { title: "Purchases and vendor payments", body: "What you owe each supplier, what you paid, and price changes from them." },
      { title: "B2B GST invoices", body: "Company bills with GSTIN, IGST for other states, and debit notes for returns." },
    ],
    faqs: [
      { q: "Can I set a credit limit for a contractor?", a: "Yes. Set an udhar limit per customer; the bill screen warns before a sale takes them over it." },
      { q: "Can I bill several delivery challans together?", a: "Yes. Make challans as goods leave, then select them and make one GST bill." },
    ],
    videos: ["04", "30"],
  },
  {
    type: "pharmacy",
    slug: "medical-store",
    mainSite: "https://www.theray.in/billing-software/pharmacy-medical-store",
    trade: "medical store",
    title: "Medical Store & Pharmacy Billing Software with Batch and Expiry",
    description: "Pharmacy billing software: batch and expiry tracking, expiry alerts and returns, salt-wise substitutes, Schedule H1 and X registers, doctor and patient on the bill, GST. Free trial.",
    h1: "Billing software for medical stores & pharmacies",
    intro: "Sell the batch that expires first, find a substitute by salt when a brand is out of stock, and keep the Schedule H1 and X registers without a separate book.",
    alsoKnownAs: ["pharmacy billing software", "medical shop billing app", "chemist billing software"],
    features: [
      { title: "Batch and expiry", body: "Stock by batch with expiry dates; billing picks the earliest-expiring batch first." },
      { title: "Expiry alerts and returns", body: "See what is about to expire and return it to the distributor or write it off." },
      { title: "Substitutes by salt", body: "Search by salt; when a medicine is out of stock, other brands of the same salt are suggested." },
      { title: "Schedule H1 and X registers", body: "Prescription items record the doctor and patient and fill the registers for inspection." },
      { title: "Rack and schedule on each item", body: "Know where a medicine sits and which schedule it falls under." },
      { title: "Doctor-wise sales", body: "See sales by prescribing doctor." },
    ],
    faqs: [
      { q: "Does it track batch and expiry?", a: "Yes. Every purchase is stocked by batch with its expiry, the bill shows batch and expiry, and expiry alerts list what to return or write off." },
      { q: "Can it suggest a substitute medicine?", a: "Yes. Medicines carry their salt; if one is out of stock, the app shows other brands with the same salt." },
    ],
    videos: ["05", "29"],
  },
  {
    type: "restaurant",
    slug: "restaurant",
    mainSite: "https://www.theray.in/billing-software/restaurant-cafe",
    trade: "restaurant",
    title: "Restaurant & Café Billing Software with KOT, Kitchen Display and QR Orders",
    description: "Restaurant POS: tables, KOT to the kitchen, kitchen display, QR table ordering, split bills, recipes and food cost, GST bills. One price for everything. Free trial.",
    h1: "Billing software for restaurants & cafés",
    intro: "From the table to the kitchen to the bill: orders go to the kitchen as a KOT, the kitchen screen shows what's ready, and every plate's food cost is known.",
    alsoKnownAs: ["restaurant POS software", "cafe billing app", "KOT software", "restaurant billing app India"],
    features: [
      { title: "Tables and KOT", body: "Open a table, add dishes with spice level and add-ons, and send the KOT to the kitchen." },
      { title: "Kitchen display", body: "The kitchen sees orders on a screen and marks dishes ready; waiters get a chime." },
      { title: "QR table ordering", body: "Guests scan a QR on the table, see the menu and order; it comes to you to confirm." },
      { title: "Split payment and company bills", body: "Split a bill across cash, UPI and card; GST invoices for companies." },
      { title: "Recipes and food cost", body: "What one plate takes, its cost, kitchen stock that falls with each order, and profit by dish." },
      { title: "Reservations and reports", body: "Bookings with a token; day-wise, item-wise and payment-mix reports." },
    ],
    faqs: [
      { q: "Can waiters take orders on their phones?", a: "Yes. Waiters and captains get their own logins, take orders at the table and send the KOT; the kitchen sees it on its display." },
      { q: "Does it work with a thermal printer?", a: "Yes. 58 mm and 80 mm Bluetooth thermal printers print KOTs and bills straight from the phone; on a computer, any printer connected to it works, and A4 suits company invoices." },
    ],
    videos: ["06", "27"],
  },
  {
    type: "hotel",
    slug: "hotel",
    mainSite: "https://www.theray.in/billing-software/hotel-lodge",
    trade: "hotel or lodge",
    title: "Hotel & Lodge Billing Software — Bookings, Room Board and GST Check-out",
    description: "Hotel management and billing: room board, booking calendar, OTA bookings and commission, check-in with ID, room service charged to the room, guest folio and GST check-out invoice.",
    h1: "Billing software for hotels & lodges",
    intro: "See every room at a glance, take bookings from the front desk or online travel sites, charge room service to the room, and check out with one GST invoice.",
    alsoKnownAs: ["hotel management software", "lodge billing software", "hotel billing app India"],
    features: [
      { title: "Room board", body: "Every room's status — free, booked, occupied, cleaning or out of service — on one screen." },
      { title: "Bookings and calendar", body: "Dates, room, guest, meal plan and advance; bookings from OTAs with their commission." },
      { title: "Check-in with ID", body: "Record the guest's ID at check-in for the guest register." },
      { title: "Room service to the room", body: "Food and extras are charged to the room and appear on the guest folio." },
      { title: "Check-out GST invoice", body: "One invoice for the stay and everything charged, paid now or kept on account." },
      { title: "Hotel reports", body: "Hotel reports and the guest register." },
    ],
    faqs: [
      { q: "Can I add bookings from Booking.com or MakeMyTrip?", a: "Yes. Choose the booking source and the OTA's commission when you add the booking, so reports show what you really earned." },
      { q: "Does it handle the restaurant too?", a: "Yes. Restaurant orders and room service can be charged to a room and come on the guest's check-out invoice." },
    ],
    videos: ["07", "27"],
  },
  {
    type: "rental",
    slug: "rental-business",
    mainSite: "https://www.theray.in/billing-software/rental-business",
    trade: "rental business",
    title: "Rental Business Software — Bookings, Deposits, Availability and Returns",
    description: "Billing for rental shops (tent, furniture, costume, equipment, vehicles): bookings with dates, deposits, availability calendar with clash blocking, pickup and return, photos.",
    h1: "Billing software for rental businesses",
    intro: "Never rent out the same item twice for the same dates: bookings block availability, deposits are tracked, and the return is checked against what went out.",
    alsoKnownAs: ["rental billing software", "tent house software", "equipment rental software"],
    features: [
      { title: "Bookings with dates", body: "Customer, items, dates and rates in one booking." },
      { title: "Availability calendar", body: "See what's free on which dates; a clashing booking is blocked." },
      { title: "Deposits", body: "Take a deposit with the booking and settle it at return." },
      { title: "Pickup and return", body: "Mark items picked up and returned; photos record their condition." },
      { title: "Rental history", body: "Every rental per customer and per item." },
      { title: "Sales too", body: "Sell items normally alongside rentals, with the same stock and GST." },
    ],
    faqs: [
      { q: "Does it stop double bookings?", a: "Yes. When an item is already booked for those dates, the app shows the clash and won't book it again." },
      { q: "Can I take photos of items before renting them out?", a: "Yes. Photos can be attached to a rental to record the item's condition." },
    ],
    videos: ["08", "31"],
  },
  {
    type: "transport",
    slug: "transport-and-building-material",
    mainSite: "https://www.theray.in/billing-software/transport-sand-materials",
    trade: "transport and building material business",
    title: "Transport & Building Material Billing Software — Bilty (LR), Trips and Vehicle Profit",
    description: "Billing for transporters and material suppliers: bilty/LR with tracking link, transport charges on bills, per-km rates, trip expenses and diesel, vehicle documents, vehicle-wise profit.",
    h1: "Billing software for transport & building material",
    intro: "Bill sand, gravel or bricks with the transport charge, make the bilty for each trip, and see what each vehicle really earns after diesel and expenses.",
    alsoKnownAs: ["transport billing software", "bilty software", "LR software", "building material supplier billing"],
    features: [
      { title: "Material bill with transport", body: "Add the transport charge to the material bill, worked out from the vehicle's per-km rate." },
      { title: "Bilty (LR)", body: "Make the lorry receipt with freight and who pays, print copies and share a tracking link." },
      { title: "Trip expenses", body: "Diesel, tolls and other expenses per trip, with the vehicle's average." },
      { title: "Vehicle documents", body: "Insurance, permit and fitness dates, with the ones about to expire listed." },
      { title: "Monthly freight bill", body: "One bill for a party's trips in the month." },
      { title: "Vehicle profit", body: "Earnings minus expenses for every vehicle." },
    ],
    faqs: [
      { q: "Can I make a bilty (LR) in the app?", a: "Yes. Make the LR with freight and who pays, print it, and share a link the customer can use to track the delivery." },
      { q: "Can it warn me before a vehicle's insurance expires?", a: "Yes. Save each vehicle's document dates and the app lists the ones about to expire." },
    ],
    videos: ["09", "26"],
  },
  {
    type: "service",
    slug: "repair-shop",
    mainSite: "https://www.theray.in/billing-software/repair-service-center",
    trade: "repair shop",
    title: "Repair Shop & Service Centre Software — Job Cards, Estimates and Status Link",
    description: "Job card software for mobile, laptop, appliance and vehicle repair: job card, estimate and advance, technician, parts from stock, customer approval and job-status link, billing on delivery.",
    h1: "Billing software for repair shops & service centres",
    intro: "Open a job card when the device comes in, get the customer's approval on the estimate, and let them check the status themselves instead of calling you.",
    alsoKnownAs: ["job card software", "mobile repair shop software", "service centre billing software"],
    features: [
      { title: "Job cards", body: "Customer, device, issue, estimate and advance on one card." },
      { title: "Estimate approval", body: "Send the estimate; the customer approves it from a link." },
      { title: "Technicians", body: "Assign each job and see who is working on what." },
      { title: "Parts from stock", body: "Parts used come out of stock and onto the bill." },
      { title: "Job-status link", body: "Customers see 'in progress' or 'ready' without calling." },
      { title: "Bill on delivery", body: "Deliver the job and bill it, with the advance adjusted." },
    ],
    faqs: [
      { q: "Can customers check if their repair is ready?", a: "Yes. Each job has a status link you can send on WhatsApp; it shows whether the job is in progress or ready." },
      { q: "Can I take an advance with the job?", a: "Yes. Record the estimate and any advance when you open the job card; it is adjusted on the final bill." },
    ],
    videos: ["10", "31"],
  },
  {
    type: "salon",
    slug: "salon-and-spa",
    mainSite: "https://www.theray.in/billing-software/salon-spa",
    trade: "salon or spa",
    title: "Salon & Spa Software — Appointments, Online Booking, Packages and Commission",
    description: "Salon billing and appointment software: online booking page, stylist on each service, commission, packages and prepaid balance, WhatsApp appointment reminders, staff-wise revenue.",
    h1: "Billing software for salons & spas",
    intro: "Clients book online, every service is billed to the stylist who did it, packages and prepaid balances are tracked, and commission is worked out for you.",
    alsoKnownAs: ["salon software", "beauty parlour billing app", "spa management software"],
    features: [
      { title: "Appointments and online booking", body: "Today's schedule and a public booking page clients can use themselves." },
      { title: "Stylist on each service", body: "Each line of the bill carries the stylist, for revenue and commission." },
      { title: "Commission", body: "Commission rates per stylist, added to their salary sheet." },
      { title: "Packages", body: "Sell packages and use them visit by visit." },
      { title: "Prepaid balance", body: "Clients pay in advance and spend it over later visits." },
      { title: "Reminders", body: "WhatsApp appointment reminders so fewer clients miss their slot." },
    ],
    faqs: [
      { q: "Can clients book an appointment online?", a: "Yes. Your salon gets a booking page; bookings appear in your appointments list." },
      { q: "Does it calculate stylist commission?", a: "Yes. Set a rate per stylist; commission is worked out from the services on each bill and can go into their salary." },
    ],
    videos: ["11", "25"],
  },
  {
    type: "jewellery",
    slug: "jewellery-shop",
    mainSite: "https://www.theray.in/billing-software/jewellery-shop",
    trade: "jewellery shop",
    title: "Jewellery Shop Billing Software — Daily Rate, Making Charge, HUID and Old Gold",
    description: "Jewellery billing: daily gold and silver rate by karat, weight, making charge and wastage, HUID on the bill, old gold exchange, gold saving scheme with passbook, karigar register.",
    h1: "Billing software for jewellery shops",
    intro: "Today's rate for each karat, making charge and wastage worked out on the weight, old gold taken in exchange, and gold saving schemes with a WhatsApp passbook.",
    alsoKnownAs: ["jewellery billing software", "gold shop billing app", "jewellery shop software India"],
    features: [
      { title: "Daily rate by karat", body: "Set today's gold and silver rates once; every bill uses them." },
      { title: "Weight, making and wastage", body: "Bill by weight with making charge, wastage and GST shown clearly." },
      { title: "HUID on the bill", body: "Record each piece's HUID and show it on the invoice." },
      { title: "Old gold exchange", body: "Weigh, set purity and value old gold, adjusted on the same bill." },
      { title: "Gold saving scheme", body: "Monthly instalments with a passbook sent on WhatsApp, used to buy at the end." },
      { title: "Karigar register", body: "Metal given to the karigar and pieces received back." },
    ],
    faqs: [
      { q: "Can I exchange old gold on the same bill?", a: "Yes. Enter the old gold's weight and purity; its value at today's rate is adjusted against the new piece on one invoice." },
      { q: "Does it support gold saving schemes?", a: "Yes. Start a scheme, record instalments, send the passbook on WhatsApp and use the scheme value on the final bill." },
    ],
    videos: ["12", "24"],
  },
  {
    type: "clinic",
    slug: "clinic-and-doctor",
    mainSite: "https://www.theray.in/billing-software/clinic-doctor",
    trade: "clinic",
    title: "Clinic Software for Doctors — Appointments, Prescriptions and Billing",
    description: "Clinic management for doctors: appointments and online booking, prescriptions on your letterhead with medicine templates, follow-ups, treatment plans, consultation billing.",
    h1: "Software for clinics & doctors",
    intro: "Write a prescription in a minute from your own medicine library, print it on your letterhead, bill the consultation, and remind patients of their follow-up.",
    alsoKnownAs: ["clinic management software", "doctor prescription app", "clinic billing software India"],
    features: [
      { title: "Appointments", body: "Today's list and an online booking page for patients." },
      { title: "Prescriptions", body: "Complaints, diagnosis, medicines with dose and duration, printed on your letterhead." },
      { title: "Medicine library and templates", body: "Your common medicines and prescriptions, ready to reuse." },
      { title: "Follow-ups", body: "A follow-up date on the prescription, free follow-ups if you allow them, and reminders." },
      { title: "Treatment plans", body: "Multi-visit plans with a quotation that turns into a bill." },
      { title: "Consultation billing", body: "Bill the visit with GST if you need it." },
    ],
    faqs: [
      { q: "Can I print prescriptions on my letterhead?", a: "Yes. Set up your prescription pad once — name, qualification, clinic details — and every prescription prints on it." },
      { q: "Can patients book appointments online?", a: "Yes. Your clinic gets a booking page; bookings appear in today's appointments." },
    ],
    videos: ["13", "29"],
  },
  {
    type: "gym",
    slug: "gym",
    mainSite: "https://www.theray.in/billing-software/gym-fitness",
    trade: "gym",
    title: "Gym Management Software — Memberships, Attendance, Leads and Renewal Reminders",
    description: "Gym software: membership plans and invoices, attendance with self check-in, classes, leads, workout and diet plans, WhatsApp renewal reminders.",
    h1: "Software for gyms & fitness centres",
    intro: "Sell memberships, let members check themselves in at the door, follow up on enquiries, and remind members before their membership runs out.",
    alsoKnownAs: ["gym management software", "fitness centre software", "gym billing app"],
    features: [
      { title: "Memberships", body: "Plans with duration and price; invoices when you sell one." },
      { title: "Attendance and self check-in", body: "Members check in at a kiosk at the door; you see who came." },
      { title: "Classes", body: "Class schedule and bookings." },
      { title: "Leads", body: "Enquiries by stage until they join." },
      { title: "Workout and diet", body: "Plans and progress on each member's profile." },
      { title: "Renewal reminders", body: "WhatsApp reminders before memberships expire." },
    ],
    faqs: [
      { q: "Can members check in themselves?", a: "Yes. Put the self check-in kiosk on a phone or tablet at the door; members check in with their number." },
      { q: "Does it remind members to renew?", a: "Yes. Members whose plan is about to end are listed for a WhatsApp reminder." },
    ],
    videos: ["14", "29"],
  },
  {
    type: "lab",
    slug: "pathology-lab",
    mainSite: "https://www.theray.in/billing-software/lab-diagnostics",
    trade: "pathology lab",
    title: "Pathology Lab Software — Test Orders, Home Collection, Reports and Billing",
    description: "Lab management software: test catalogue and packages, orders with home collection charge, sample stickers, result entry, printable reports, billing.",
    h1: "Software for pathology & diagnostic labs",
    intro: "Book tests and packages, collect samples at home, label them with stickers, enter results and print a clean report — then bill it in the same place.",
    alsoKnownAs: ["pathology lab software", "diagnostic centre software", "lab report software"],
    features: [
      { title: "Test catalogue and packages", body: "Your tests, prices and profiles in one list." },
      { title: "Orders and home collection", body: "Patient, tests and a home collection charge." },
      { title: "Sample stickers", body: "Print stickers; scan one to open the order." },
      { title: "Results and reports", body: "Enter results and print the report." },
      { title: "Billing", body: "Bill the order with or without GST." },
      { title: "Pending work", body: "Pending orders and home collections on the dashboard." },
    ],
    faqs: [
      { q: "Can I print sample stickers?", a: "Yes. Each order prints sample stickers; scanning one opens that order." },
      { q: "Can I charge for home collection?", a: "Yes. Add the home collection charge when you create the order." },
    ],
    videos: ["15", "29"],
  },
  {
    type: "wholesale",
    slug: "wholesale-distributor",
    trade: "wholesale or distribution business",
    title: "Wholesale & Distributor Billing Software — Party Rates, Schemes and Collections",
    description: "Distribution billing: rate list from MRP, party-wise rates and terms, company schemes, salesman orders, bills with due dates, payment collection (vasooli), GST.",
    h1: "Billing software for wholesalers & distributors",
    intro: "Each party gets its own rate and scheme, salesmen's orders turn into bills with a due date, and you always know who owes how much.",
    alsoKnownAs: ["distributor billing software", "wholesale billing app", "FMCG distributor software"],
    features: [
      { title: "Rate list from MRP", body: "Set rates from MRP with your margins." },
      { title: "Party rates and terms", body: "Different rates, schemes and credit days for each party." },
      { title: "Company schemes", body: "Schemes on purchases and on the bill, with a scheme report." },
      { title: "Salesman orders", body: "Orders taken in the field become bills." },
      { title: "Due dates and vasooli", body: "Bills with due dates and a list of payments due." },
      { title: "Delivery challans", body: "Goods on a challan, billed together later." },
    ],
    faqs: [
      { q: "Can different parties have different rates?", a: "Yes. Each party can have its own rates, schemes and payment terms, applied when you bill them." },
      { q: "Can I see which payments are due?", a: "Yes. Bills carry a due date and the payments-due list shows who owes what and since when." },
    ],
    videos: ["32", "30"],
  },
  {
    type: "general",
    slug: "general-store",
    mainSite: "https://www.theray.in/billing-software/general-store",
    trade: "shop",
    title: "Free GST Billing App for Any Shop — Bills, Udhar, Stock and Reports",
    description: "Simple billing app for any shop or business: GST and non-GST bills, udhar khata, stock, purchases, sales returns, reports, WhatsApp bills. Works on any phone. Free trial.",
    h1: "Billing software for any shop",
    intro: "Whatever you sell, bill it with or without GST, keep udhar in a khata, track stock and purchases, and send the bill on WhatsApp.",
    alsoKnownAs: ["billing app for small business", "GST billing app", "shop billing software", "invoice app India"],
    features: [
      { title: "GST and non-GST bills", body: "Inclusive or exclusive prices, CGST/SGST or IGST, A4 or thermal." },
      { title: "Udhar khata", body: "Part payments, balances and WhatsApp reminders." },
      { title: "Stock and purchases", body: "Stock in from purchases, out with sales." },
      { title: "Sales returns", body: "Returns adjusted against udhar or refunded." },
      { title: "Reports", body: "Daily summary, sales, profit and GST returns." },
      { title: "WhatsApp bills", body: "Send the bill or a PDF on WhatsApp in one tap." },
    ],
    faqs: [
      { q: "Do I need GST registration to use it?", a: "No. You can make bills without GST; switch GST on when you register." },
      { q: "Can I send bills on WhatsApp?", a: "Yes. Share the full bill, a PDF or a link the customer can open." },
    ],
    videos: ["16", "21"],
  },
];

export const verticalBySlug = (slug: string) => VERTICALS.find((v) => v.slug === slug);
/** Where a trade's page is: the main site's, or this site's own. */
export const verticalHref = (v: Vertical) => v.mainSite ?? `/billing-software/${v.slug}`;
export const MAIN_SITE_TRADES = "https://www.theray.in/billing-software";
export const verticalForType = (type: string) => VERTICALS.find((v) => v.type === type);
