// A genuinely useful (not exhaustive) library of common device models
// per category, so staff can search "Redmi Note 13" or "Activa" and
// get it filled in instantly instead of typing it out every time.
// Covers the brands/models most commonly seen in Indian repair shops.

export type DeviceModel = { brand: string; model: string };

const MOBILE_MODELS: DeviceModel[] = [
  { brand: "Samsung", model: "Galaxy S24" },
  { brand: "Samsung", model: "Galaxy S23" },
  { brand: "Samsung", model: "Galaxy A54" },
  { brand: "Samsung", model: "Galaxy A34" },
  { brand: "Samsung", model: "Galaxy M14" },
  { brand: "Samsung", model: "Galaxy F14" },
  { brand: "Apple", model: "iPhone 15" },
  { brand: "Apple", model: "iPhone 14" },
  { brand: "Apple", model: "iPhone 13" },
  { brand: "Apple", model: "iPhone 12" },
  { brand: "Apple", model: "iPhone SE" },
  { brand: "Xiaomi", model: "Redmi Note 13" },
  { brand: "Xiaomi", model: "Redmi Note 12" },
  { brand: "Xiaomi", model: "Redmi 13C" },
  { brand: "Xiaomi", model: "Redmi A3" },
  { brand: "Xiaomi", model: "Mi 11X" },
  { brand: "Xiaomi", model: "POCO X6" },
  { brand: "Xiaomi", model: "POCO M6" },
  { brand: "Realme", model: "Realme 12" },
  { brand: "Realme", model: "Realme Narzo 60" },
  { brand: "Realme", model: "Realme C55" },
  { brand: "Realme", model: "Realme GT 6" },
  { brand: "Oppo", model: "Oppo A78" },
  { brand: "Oppo", model: "Oppo Reno 11" },
  { brand: "Oppo", model: "Oppo F25" },
  { brand: "Vivo", model: "Vivo Y28" },
  { brand: "Vivo", model: "Vivo V30" },
  { brand: "Vivo", model: "Vivo T3" },
  { brand: "OnePlus", model: "OnePlus 12" },
  { brand: "OnePlus", model: "OnePlus Nord CE4" },
  { brand: "OnePlus", model: "OnePlus 11R" },
  { brand: "Motorola", model: "Moto G84" },
  { brand: "Motorola", model: "Moto Edge 40" },
  { brand: "Google", model: "Pixel 8" },
  { brand: "Google", model: "Pixel 7a" },
  { brand: "Nokia", model: "Nokia G42" },
  { brand: "Infinix", model: "Infinix Note 40" },
  { brand: "Tecno", model: "Tecno Spark 20" },
];

const BIKE_MODELS: DeviceModel[] = [
  { brand: "Honda", model: "Activa 6G" },
  { brand: "Honda", model: "Shine" },
  { brand: "Honda", model: "Unicorn" },
  { brand: "Honda", model: "SP 125" },
  { brand: "Bajaj", model: "Pulsar 150" },
  { brand: "Bajaj", model: "Pulsar NS200" },
  { brand: "Bajaj", model: "Platina" },
  { brand: "Bajaj", model: "CT 100" },
  { brand: "TVS", model: "Jupiter" },
  { brand: "TVS", model: "Apache RTR 160" },
  { brand: "TVS", model: "Ntorq 125" },
  { brand: "TVS", model: "Sport" },
  { brand: "Hero", model: "Splendor Plus" },
  { brand: "Hero", model: "HF Deluxe" },
  { brand: "Hero", model: "Glamour" },
  { brand: "Hero", model: "Xtreme 160R" },
  { brand: "Yamaha", model: "FZ-S" },
  { brand: "Yamaha", model: "R15" },
  { brand: "Yamaha", model: "Fascino 125" },
  { brand: "Royal Enfield", model: "Classic 350" },
  { brand: "Royal Enfield", model: "Bullet 350" },
  { brand: "Royal Enfield", model: "Hunter 350" },
  { brand: "Suzuki", model: "Access 125" },
  { brand: "Suzuki", model: "Gixxer" },
  { brand: "KTM", model: "Duke 200" },
  { brand: "KTM", model: "Duke 390" },
];

const CAR_MODELS: DeviceModel[] = [
  { brand: "Maruti Suzuki", model: "Swift" },
  { brand: "Maruti Suzuki", model: "Baleno" },
  { brand: "Maruti Suzuki", model: "WagonR" },
  { brand: "Maruti Suzuki", model: "Alto K10" },
  { brand: "Maruti Suzuki", model: "Dzire" },
  { brand: "Maruti Suzuki", model: "Ertiga" },
  { brand: "Maruti Suzuki", model: "Brezza" },
  { brand: "Hyundai", model: "i20" },
  { brand: "Hyundai", model: "Creta" },
  { brand: "Hyundai", model: "Venue" },
  { brand: "Hyundai", model: "Grand i10 Nios" },
  { brand: "Hyundai", model: "Verna" },
  { brand: "Tata", model: "Nexon" },
  { brand: "Tata", model: "Punch" },
  { brand: "Tata", model: "Tiago" },
  { brand: "Tata", model: "Altroz" },
  { brand: "Mahindra", model: "Scorpio-N" },
  { brand: "Mahindra", model: "XUV700" },
  { brand: "Mahindra", model: "Bolero" },
  { brand: "Mahindra", model: "XUV300" },
  { brand: "Honda", model: "City" },
  { brand: "Honda", model: "Amaze" },
  { brand: "Toyota", model: "Innova Crysta" },
  { brand: "Toyota", model: "Fortuner" },
  { brand: "Toyota", model: "Glanza" },
  { brand: "Kia", model: "Seltos" },
  { brand: "Kia", model: "Sonet" },
  { brand: "Renault", model: "Kwid" },
  { brand: "Renault", model: "Triber" },
];

const LAPTOP_MODELS: DeviceModel[] = [
  { brand: "Dell", model: "Inspiron 15" },
  { brand: "Dell", model: "Vostro 14" },
  { brand: "Dell", model: "Latitude" },
  { brand: "Dell", model: "XPS 13" },
  { brand: "HP", model: "Pavilion 15" },
  { brand: "HP", model: "15s" },
  { brand: "HP", model: "ProBook" },
  { brand: "HP", model: "Envy" },
  { brand: "Lenovo", model: "IdeaPad Slim 3" },
  { brand: "Lenovo", model: "ThinkPad E14" },
  { brand: "Lenovo", model: "Legion 5" },
  { brand: "Lenovo", model: "V15" },
  { brand: "Asus", model: "Vivobook 15" },
  { brand: "Asus", model: "ROG Strix" },
  { brand: "Asus", model: "Zenbook" },
  { brand: "Acer", model: "Aspire 5" },
  { brand: "Acer", model: "Nitro 5" },
  { brand: "Apple", model: "MacBook Air M2" },
  { brand: "Apple", model: "MacBook Pro 14" },
  { brand: "MSI", model: "Modern 14" },
  { brand: "MSI", model: "Katana" },
];

export function modelsFor(category: string | null): DeviceModel[] {
  if (category === "mobile") return MOBILE_MODELS;
  if (category === "bike") return BIKE_MODELS;
  if (category === "car") return CAR_MODELS;
  if (category === "laptop") return LAPTOP_MODELS;
  return [];
}
