// The training videos (generated from the recordings — scratchpad video/gen-videos-ts.mjs).
// Each chapter is one short Hinglish video. It plays from YouTube when the team has set its link
// (lib/youtubeData.ts), else from the public "training-videos" storage bucket as NN.mp4 (phone size).
// The poster NN.jpg and subtitles NN.vtt ship with the app in public/training-videos, so lists of
// videos cost the storage bucket nothing. `for` says which trades it is about.

export type TrainingVideo = { id: string; title: string; seconds: number; for: "all" | string[]; topics: [seconds: number, title: string][] };

export const TRAINING_VIDEOS: TrainingVideo[] = [
  { id: "01", title: "The Ray – Common Billing & Dashboard", seconds: 508, for: "all", topics: [[22,"Demo page"],[43,"Open the grocery demo"],[54,"Home screen: health score"],[74,"Home: sales, to collect, to pay"],[92,"Home: 7-day trend and recent bills"],[106,"Home: festival reminder, shortcuts"],[120,"New bill: choose a customer"],[137,"New bill: add items"],[152,"New bill: quantity"],[168,"New bill: discount and GST"],[188,"Payment: part payment and udhaar"],[211,"Invoice generated"],[233,"Bill formats: A4, 58mm, 80mm"],[255,"Print, PDF and WhatsApp"],[271,"Customer khata"],[287,"Customer khata: balance, history, remind"],[308,"Record a payment"],[321,"Khata updated"],[335,"Reports overview"],[360,"Report: Daily summary"],[381,"Report: GSTR-1"],[406,"Report: GSTR-3B"],[428,"Report: Purchase register"],[441,"Report: Profit leak"],[456,"Preferences: language"],[472,"Preferences: dark mode"]] },
  { id: "02", title: "Grocery / Kirana – Complete Workflow", seconds: 435, for: ["grocery"], topics: [[22,"Dashboard: sales, udhaar, low stock, health"],[49,"Fast Billing"],[72,"Fast Billing: cart and payment"],[91,"New Bill: search or scan"],[109,"Suggestions and part payment"],[129,"Customers: khata and payments"],[159,"Udhaar reminders"],[178,"Loyalty program"],[196,"Birthdays"],[217,"Products: GST, HSN, stock, barcode"],[241,"Barcode labels"],[256,"Purchases"],[281,"Reorder low stock"],[297,"Vendor price comparison"],[315,"Report: Daily summary"],[332,"Reports: GSTR-1, GSTR-3B, Purchase register"],[357,"Profit leak"],[385,"Insights and udhaar aging"]] },
  { id: "03", title: "Supermarket / Mart – Fast Counter Billing", seconds: 274, for: ["mart"], topics: [[17,"Fast Billing counter"],[45,"Fast Billing: cart and payment"],[61,"New Bill: MRP and offers"],[79,"Offer price on the bill"],[96,"Bulk pricing"],[113,"Products: offer price and bulk rates"],[134,"Stock audit: start a count"],[150,"Stock audit: enter counts"],[169,"Stock audit: settle mismatch"],[184,"Reorder low stock"],[211,"Reorder: pre-filled purchase"],[223,"Dashboard"],[235,"Profit leak"]] },
  { id: "04", title: "Hardware / Building Material – Warranty & Contractor Udhaar", seconds: 251, for: ["hardware"], topics: [[19,"Dashboard: receivables and payables"],[38,"New bill with warranty items"],[52,"Part payment, rest on udhaar"],[71,"Invoice with warranty record"],[82,"Customers: contractors and udhaar"],[104,"Contractor khata and reminder"],[127,"Warranty lookup by phone"],[138,"Warranty result"],[154,"Purchases hub"],[170,"Vendor payments"],[198,"Products: bulk rates, stock, reorder level"],[219,"Dashboard"]] },
  { id: "05", title: "Pharmacy / Medical Store – Batch, Expiry & Schedule", seconds: 250, for: ["pharmacy"], topics: [[21,"Dashboard: expiry and stock warnings"],[43,"New bill: choose medicines"],[60,"Prescription item: doctor and patient"],[80,"Invoice with batch and expiry"],[94,"Products: salt, rack, schedule"],[114,"Batches and expiry per medicine"],[141,"Expiry alerts and return to distributor"],[166,"Write-offs"],[185,"Schedule H1 and X register"],[211,"Doctor-wise sales"]] },
  { id: "06", title: "Restaurant / Cafe – Table to Kitchen to Bill", seconds: 351, for: ["restaurant"], topics: [[20,"Tables screen"],[43,"Open a table"],[57,"Order screen: order type and waiter"],[72,"Dish options: spice level and add-ons"],[96,"Add dishes to the order"],[111,"Send KOT to the kitchen"],[128,"Kitchen display screen"],[146,"Mark dish ready"],[162,"Settle the bill"],[175,"Split payment and confirm"],[194,"Combos"],[211,"Reservations with token"],[230,"Book with token"],[246,"Reports: day-wise and payment mix"],[265,"Reports: item-wise and category-wise"],[285,"Menu options setup"],[299,"Kitchen display settings"],[312,"Menu PDF"]] },
  { id: "07", title: "Hotel / Lodge – Booking to Check-out", seconds: 453, for: ["hotel"], topics: [[18,"Front desk"],[43,"Room board"],[63,"Room actions: cleaning and out of service"],[80,"Booking calendar"],[102,"Bookings list and search"],[119,"New booking: dates, room, guest"],[131,"Booking source, OTA and commission"],[153,"Meal plan, advance, save booking"],[170,"Booking page and guest account"],[190,"Check-in with ID"],[204,"Add an extra charge"],[238,"Room service order"],[255,"Charge room service to the room"],[292,"Guest folio"],[313,"Check-out: payment and udhaar"],[338,"Check-out GST invoice"],[359,"Hotel reports"],[383,"Guest register"],[402,"Hotel setup"]] },
  { id: "08", title: "Rental Business – Booking, Deposit & Return", seconds: 279, for: ["rental"], topics: [[22,"Rentals list and status"],[44,"New rental: customer"],[53,"Rental: dates, items, rates"],[74,"Deposit and payment"],[94,"Availability and date-clash blocking"],[118,"Confirm the booking"],[144,"Availability calendar"],[163,"Mark picked up"],[180,"Return workflow"],[205,"Rental history"],[221,"Products: rental rates and deposit"],[244,"Ordinary sales alongside rentals"]] },
  { id: "09", title: "Transport & Materials – Material + Vehicle Trip", seconds: 208, for: ["transport"], topics: [[22,"Material sale"],[36,"Transport charge on the bill"],[62,"Complete the bill"],[82,"Invoice with transport line"],[99,"Vehicles and per-km rates"],[122,"Vehicle documents and expiry"],[142,"Customers and udhaar"],[163,"Vehicle-wise trip report"]] },
  { id: "10", title: "Repair & Services – Job Card to Delivery", seconds: 229, for: ["service"], topics: [[18,"Jobs list and status"],[43,"New job: customer, device, issue"],[63,"Estimate, advance and create the job"],[81,"Add parts from stock"],[108,"Assign the technician"],[125,"Status: in progress and ready"],[146,"Customer job-status link"],[162,"Deliver and bill the job"],[182,"Service reports"]] },
  { id: "11", title: "Salon / Spa – Appointment to Stylist Revenue", seconds: 240, for: ["salon"], topics: [[22,"Appointments: today's schedule"],[50,"Book an appointment"],[85,"Mark the customer arrived"],[96,"Bill a service"],[111,"Stylist on the bill"],[128,"Invoice generated"],[142,"Customers: visits and history"],[168,"Online booking settings"],[191,"Staff-wise revenue"],[210,"Dashboard"]] },
  { id: "12", title: "Jewellery – Rate, Making, HUID & Old Gold Exchange", seconds: 225, for: ["jewellery"], topics: [[22,"Daily gold and silver rate"],[45,"Jewellery item: name, HUID, weight"],[61,"Making charge, wastage and GST"],[86,"Old gold exchange on the bill"],[103,"Exchange weight, purity and value"],[126,"Invoice with exchange"],[145,"Exchange history"],[170,"Products: coins, bars, silver articles"],[190,"Dashboard"]] },
  { id: "13", title: "Clinic / Doctor – Appointment to Prescription to Bill", seconds: 300, for: ["clinic"], topics: [[19,"Appointments: today's list"],[46,"New prescription: patient"],[64,"Complaints, diagnosis and specialty fields"],[85,"Medicines, dose and duration"],[112,"Follow-up date and template"],[130,"Print prescription on letterhead"],[155,"Bill the consultation"],[169,"Treatment plans"],[189,"Quotation and convert to bill"],[212,"Medicine library"],[233,"Prescription pad settings"],[256,"Online booking settings"]] },
  { id: "14", title: "Gym / Fitness – Lead to Membership to Attendance", seconds: 292, for: ["gym"], topics: [[20,"Members: status and actions"],[47,"Sell a membership"],[72,"Membership invoice"],[90,"Membership plans"],[109,"Attendance"],[127,"Check in a member"],[144,"Classes and bookings"],[166,"Leads by stage"],[195,"Self check-in kiosk"],[214,"Member profile: workout plan"],[249,"Member profile: diet and progress"]] },
  { id: "15", title: "Lab / Diagnostics – Test Order to Report", seconds: 249, for: ["lab"], topics: [[19,"Test catalogue"],[43,"Packages and profiles"],[61,"New order: patient and home collection"],[79,"Choose tests and create the order"],[101,"Order statuses"],[126,"Orders list and pending orders"],[148,"Enter test results"],[170,"Printable report"],[195,"Bill the order"],[209,"Dashboard: pending orders and home collections"]] },
  { id: "16", title: "General Store / Other – Flexible Billing", seconds: 284, for: ["general"], topics: [[23,"Dashboard"],[40,"New bill"],[59,"Discount and full udhaar"],[74,"Invoice and sales return"],[98,"Customer and udhaar"],[114,"Products: add an item"],[143,"Products and stock"],[162,"Purchases"],[181,"Save the purchase"],[194,"Reports and GST"],[218,"GSTR-1"],[236,"Common bill outputs"]] },
  { id: "17", title: "Reports, GST & Settings – Back Office Masterclass", seconds: 550, for: "all", topics: [[23,"Reports hub"],[49,"Daily summary"],[74,"Staff-wise daily breakdown"],[94,"Sales report"],[116,"Profit report"],[139,"GSTR-1"],[172,"GSTR-3B"],[200,"Purchase register"],[219,"Profit leak"],[237,"Export data: Excel and PDF"],[263,"CA export pack"],[285,"Petty cash"],[305,"Void a bill with a reason"],[328,"Audit log"],[349,"Settings: GST and shop profile"],[377,"Invoice design"],[394,"Thermal print settings"],[423,"Fast billing settings"],[439,"Loyalty settings"],[453,"Festival planner"],[477,"Offline billing"],[495,"Preferences: language and theme"]] },
  { id: "18", title: "Customer-Facing Features – Online Booking, Catalogue, QR & Status", seconds: 292, for: "all", topics: [[24,"Public salon booking page"],[51,"Booking appears for the owner"],[77,"Public clinic booking page"],[92,"Grocery online catalogue"],[118,"Catalogue order to owner and bill"],[141,"Restaurant online catalogue"],[164,"Restaurant QR table ordering"],[185,"Gym self check-in kiosk"],[213,"Repair job-status page"],[236,"Customer khata statement"]] },
  { id: "19", title: "Baaki Sab Features – More Menu ka Poora Tour", seconds: 436, for: "all", topics: [[20,"More menu overview"],[58,"Global search"],[77,"AI shop assistant"],[96,"Item requests"],[118,"Item requests: mark available"],[128,"Win them back"],[149,"Staff performance"],[163,"Bulk sale entry"],[185,"Import old khata (AI)"],[212,"Import old sales register (AI)"],[231,"Scan a price list (AI)"],[254,"Shelf watch (AI)"],[273,"Today's highlight card"],[290,"Staff logins and permissions"],[316,"Branches"],[335,"Plan and billing"],[363,"Help and guide"],[382,"Profile and install app"]] },
  { id: "20", title: "B2B GST Bills, Debit Notes & Corrections", seconds: 300, for: "all", topics: [[22,"Bill for an employee's company"],[38,"B2B switch and IGST"],[67,"Invoice to the company"],[93,"Debit note"],[114,"Printed debit note"],[139,"Return adjusted against udhaar"],[156,"Last month's bills are locked"],[179,"Restaurant company bill"],[197,"Hotel company invoice"],[216,"GSTR-1 B2B view"],[240,"GSTR-3B"]] },
  { id: "21", title: "Din Band Karna (Galla Ginti) & Bill ka PDF WhatsApp par", seconds: 191, for: "all", topics: [[16,"Bill for a customer"],[30,"Bill share options"],[42,"Full bill on WhatsApp"],[64,"Customer's invoice link"],[89,"Expected cash"],[113,"Opening cash"],[126,"Counting the notes"],[140,"Close the day"],[156,"Closed day and reopening"]] },
  { id: "22", title: "Quotation se Bill — Ek Tap mein", seconds: 141, for: "all", topics: [[19,"Building the quotation"],[35,"Save as quotation"],[51,"The quotation"],[69,"Customer's quotation link"],[87,"Quotations list"],[98,"Make bill from a quotation"],[113,"Billed"]] },
  { id: "23", title: "Staff Haazri aur Salary", seconds: 124, for: "all", topics: [[14,"Adding people"],[25,"Daily wage worker"],[36,"Daily attendance"],[56,"Salary sheet"],[70,"Advance"],[86,"Salary slip"],[101,"Daily summary"]] },
  { id: "24", title: "Jewellery — Karat-wise Rate aur Gold Saving Scheme", seconds: 194, for: ["jewellery"], topics: [[20,"Rate for each karat"],[56,"Rate on home"],[63,"Billing an 18K piece"],[81,"Old gold at today's rate"],[100,"Starting a scheme"],[119,"Instalments and passbook"],[134,"WhatsApp passbook"],[144,"Buying with the scheme"],[162,"Scheme on the invoice"]] },
  { id: "25", title: "Salon — Stylist Commission, Package aur Prepaid Balance", seconds: 182, for: ["salon"], topics: [[18,"Commission rates"],[33,"Making a package"],[51,"Customers' packages"],[65,"Using a package"],[85,"Stylist on each line"],[97,"Package bill"],[106,"Prepaid balance"],[120,"Paying from prepaid"],[144,"Stylist report"],[159,"Commission in salary"]] },
  { id: "26", title: "Transport — Bilty (LR), Gaadi ka Kharcha aur Munafa", seconds: 180, for: ["transport"], topics: [[20,"Bilty list"],[36,"New bilty"],[52,"Freight and who pays"],[73,"Status to delivery"],[87,"Tracking link"],[101,"Print copies"],[111,"Expense on the trip"],[121,"Diesel and average"],[137,"Monthly freight bill"],[153,"Vehicle profit"]] },
  { id: "27", title: "Restaurant — Recipe, Food Cost aur Kitchen Stock", seconds: 186, for: ["restaurant","hotel"], topics: [[19,"Recipes list"],[34,"Dish without a recipe"],[47,"New raw material"],[62,"What one plate takes"],[73,"Plate cost and food cost"],[86,"A table order"],[100,"Settle takes stock"],[111,"Kitchen stock"],[130,"Wastage"],[148,"Buying raw material"],[159,"Profit by dish"]] },
  { id: "28", title: "Plan & Billing, Aaj ke Daam, aur Support Request", seconds: 193, for: "all", topics: [[25,"Your plan"],[42,"Choosing a plan"],[61,"Compare plans"],[72,"Locks in the menu"],[83,"A locked feature"],[94,"When a plan ends"],[107,"Today's prices"],[122,"Change many at once"],[135,"Saving the prices"],[142,"Support request"],[165,"Request status"]] },
  { id: "29", title: "Dawai ka Substitute, Lab Sample Sticker aur WhatsApp Reminders", seconds: 152, for: ["pharmacy","lab","gym","salon","clinic"], topics: [[19,"Search by salt"],[34,"Out of stock → substitute"],[51,"Other brands of the same salt"],[67,"Sample stickers"],[89,"Scan to open the order"],[101,"Membership reminders"],[125,"Appointment reminders"]] },
  { id: "30", title: "Delivery Challan, Udhaar Limit, 2 Lo 1 Free aur Kaante ka Barcode", seconds: 179, for: ["hardware","grocery","mart","general","wholesale"], topics: [[19,"New delivery challan"],[49,"The challan"],[58,"One bill for many challans"],[72,"Billed"],[82,"Udhaar limit"],[92,"Over the limit warning"],[108,"Buy X get Y"],[118,"Scheme on the bill"],[139,"Scale label settings"],[158,"Scan a scale label"]] },
  { id: "31", title: "Karigar Register, Free Follow-up, Repair Estimate, Lab Home Charge aur Rental Photo", seconds: 203, for: ["jewellery","clinic","service","lab","rental"], topics: [[17,"Metal to the karigar"],[35,"Piece received"],[53,"Free follow-up setting"],[91,"Free follow-up on the bill"],[108,"Ask for approval"],[131,"Customer approves"],[144,"Lab home collection"],[162,"Rental photos"]] },
  { id: "32", title: "Wholesale / Distributor — MRP Rate, Party Rate, Scheme, Order aur Vasooli", seconds: 175, for: ["wholesale"], topics: [[26,"Rate list from MRP"],[66,"Party terms"],[75,"Company scheme on purchase"],[90,"Party rate and scheme on the bill"],[104,"Salesman order"],[117,"Order billed with a due date"],[129,"Payments due"],[142,"Scheme report"]] },
];

export const videoById = (id: string) => TRAINING_VIDEOS.find((v) => v.id === id) ?? null;

/** Where a video's files are. */
export function videoFiles(id: string, base = process.env.NEXT_PUBLIC_SUPABASE_URL ?? "") {
  return { mp4: `${base}/storage/v1/object/public/training-videos/${id}.mp4`, poster: `/training-videos/${id}.jpg`, vtt: `/training-videos/${id}.vtt` };
}

/** Width / height of every recording (a phone screen). */
export const VIDEO_ASPECT = "720 / 1558";

/** This trade's own videos first, then the ones for every shop. */
export function videosFor(businessType: string) {
  const own = TRAINING_VIDEOS.filter((v) => v.for !== "all" && v.for.includes(businessType));
  const common = TRAINING_VIDEOS.filter((v) => v.for === "all");
  const other = TRAINING_VIDEOS.filter((v) => v.for !== "all" && !v.for.includes(businessType));
  return { own, common, other };
}

/** The one video to show first for a trade: the most specific of its own (wholesale gets its own
 * chapter, not the one it shares with four other trades). */
export function mainVideoFor(businessType: string): TrainingVideo | null {
  const { own } = videosFor(businessType);
  return [...own].sort((x, y) => x.for.length - y.for.length || x.id.localeCompare(y.id))[0] ?? null;
}

export const mmss = (s: number) => `${Math.floor(s / 60)}:${String(Math.round(s % 60)).padStart(2, "0")}`;
